### ISSUE TITLE
Rename applications in modeling to projects

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#2177] opened 2018-11-19 17:29 UTC
In order to keep the analogy between the modeling app and an IDE and avoid any ambiguity with applications at runtime, applications in modeling should be renamed to projects.

As such:
* the application model type should be renamed to project
* the applications API URLs should be renamed to projects
* the application.json file in import/export should be renamed to project.json
* modeling acceptance tests should be updated

**Comment by salaboy** [comment] 2018-11-20 08:40
@mteodori who is assigned to this issue? I wouldn't add it to beta4 unless we have someone working on this right now.

**Comment by salaboy** [comment] 2018-11-20 08:42
I would propose the name **ProjectBundle** for Java classes and models such as the one contained inside the project.json file. We can keep /projects/ as endpoint. 
I've come to the conclusion that Project itself also gets confusing because you will tend to map one project with one application (at runtime) and that will confuse people, due the fact that the architecture was designed to support N to N mappings.

**Comment by salaboy** [comment] 2018-11-20 08:43
@mteodori also this module needs to be renamed: https://github.com/Activiti/Activiti/tree/develop/activiti-spring-app-process 
Let's make sure that we don't leave inconsistencies all over the place please.

**Comment by salaboy** [comment] 2018-11-20 12:06
moving to beta5 until we have someone working on it.

**Comment by salaboy** [comment] 2018-12-23 12:33
no time in Beta5, this needs to be done by RC1 
@mteodori if you can assign something to work on this will be great.

**Comment by salaboy** [comment] 2019-01-19 09:21
done and merged to develop

**Closed by salaboy** 2019-01-19 09:21 UTC
Labels: priority1, risk
