### ISSUE TITLE
Process Variables Mappings

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2433] opened 2019-01-30 08:26 UTC
following #2213 we need to improve this code and test it in our acceptance tests end to end from modeller to cloud. 
We also need the modeller UI for mappings in community.

**Comment by erdemedeiros** [comment] 2019-02-04 15:55
@salaboy what is the difference between this and https://github.com/Activiti/Activiti/issues/2213?

**Comment by salaboy** [comment] 2019-02-04 15:56
probably none.. should we use the other one? or this one?

**Comment by salaboy** [comment] 2019-02-04 15:56
let's close one

**Comment by erdemedeiros** [comment] 2019-02-04 16:13
Duplicate of https://github.com/Activiti/Activiti/issues/2213

**Comment by erdemedeiros** [comment] 2019-02-04 16:14
Closed this one because the there is already a PR referencing the other one.

**Closed by erdemedeiros** 2019-02-04 16:13 UTC
Labels: priority1
