### ISSUE TITLE
关于Activit的一点建议

### ISSUE THREAD

**Issue by SchuckBeta** [Activiti/Activiti#1649] opened 2017-12-28 14:18 UTC
在实际使用中需要做流程的自定义（关于业务的自定义，网上的流程设计界面只适合开发人员使用），关于Activit与实际业务的交互，实际上交叉点在于 业务节点上。所以建议Activit可以提供一个关于查询Activit流程模型的 UserTask 节点的API接口，这样做可以实现  脱离Activit的表结构   建立关于业务的节点数据 达到业务流程自定义的目的
![default](https://user-images.githubusercontent.com/21231746/34413293-5f504630-ec1d-11e7-8131-34a68ab9f312.png)

**Comment by Salaboy** [comment] 2018-01-31 17:19
@SchuckBeta this looks really interesting but issues should be written in english, even using the google translator will help us to quickly review what the problem is and we can help you to find a fix to your issue.

**Comment by Salaboy** [comment] 2018-01-31 17:23
@SchuckBeta using google translate I got this: "In actual use need to do the process of custom (on business customization, online process design interface is only suitable for developers to use), Activit and the actual business interaction, in fact, the intersection lies in the business node. It is recommended that Activit provide an API interface to the UserTask node that queries the Activit process model so that the table structure that is free from Activit can be established. Creating node data about the business can be customized for business processes"

I couldn't translate the chart that you provided, but it sounds like you want to create a high level abstraction to be able to change processes and bridge the gap between businesses and developers. I'm more than happy to have a chat about this idea with you in our gitter channel: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
Please drop me a message when you are available to discuss this. 
I will close this issue now, because this is not an issue and it sounds more like a proposal for a new thing.

**Closed by Salaboy** 2018-01-31 17:23 UTC
