### ISSUE TITLE
Missing processDefinitionKey in resumed process instances in query service

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2318] opened 2018-12-27 13:10 UTC
The processDefinitionKey disappears in query service after resuming a process instance previously suspended.
When suspended, the instance still keeps the field:
![image](https://user-images.githubusercontent.com/32025234/50481314-1b310600-09e1-11e9-8116-6b13598eb041.png)
When resumed, the field is gone:
![image](https://user-images.githubusercontent.com/32025234/50481332-33088a00-09e1-11e9-8336-fb9dd8ed1999.png)

**Comment by CTI777** [comment] 2019-01-03 09:09
Currently it seems that all events related to process, except of create an start should have processDefinitionKey = null
In this class org.activiti.engine.impl.cmd.AbstractSetProcessInstanceStateCmd Execute method is called, and it returns object where everything is null
ExecutionEntity executionEntity = commandContext.getExecutionEntityManager().findById(processInstanceId);

This can be used for tests...
public class ExecutionEventsTest extends PluggableActivitiTestCase

**Comment by miguelruizdev** [comment] 2019-01-03 13:14
As green tests by Illia suggest, it turns out that the missing information in the entity, is present in the event:

- In AuditProducerIT, this passes:
`assertThat(((CloudProcessResumedEvent)receivedEvents.get(0)).getProcessDefinitionKey()).isEqualTo(SIMPLE_PROCESS);`
- Whereas this doesn't:
`assertThat(((CloudProcessResumedEvent)receivedEvents.get(0)).getEntity().getProcessDefinitionKey()).isEqualTo(SIMPLE_PROCESS);`

**Comment by miguelruizdev** [comment] 2019-01-03 13:15
We wonder if this has a fix at a converter level, and where that converter might be

**Comment by salaboy** [comment] 2019-01-03 15:58
Just to be sure.. the problem is here: 
https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/ProcessResumedEventHandler.java#L50

When resuming a process we shouldn't override this data if the entity already has it stored from previous events. Also it highlights the problem of looking into the "event"."entity" to get that information and sometimes.. depending on the event that information is not available on the "entity" level.. This means that we should upgrade and unify our handlers to make sure that we consume the information from the top "event" level.

**Comment by salaboy** [comment] 2019-01-04 09:58
PRs merged.. so closing this issues..

**Closed by salaboy** 2019-01-04 09:58 UTC
