### ISSUE TITLE
Add a way to filter tasks by name and return all matching results

### ISSUE THREAD

**Issue by davidcanonieto** [Activiti/Activiti#2375] opened 2019-01-17 17:38 UTC
As a developer, I would like to have an endpoint that, given a string parameter, return all the tasks that have a name that matches the given parameter.

 Complete library: [Task 1, Task 2, TasO 3]

Call => taskContainingName('Task)
Response => [Task 1, Task 2]

**Comment by salaboy** [comment] 2019-01-19 09:08
duplicate of #1921

**Comment by salaboy** [comment] 2019-01-19 09:10
duplicate of https://github.com/Activiti/Activiti/issues/1954

**Closed** 2019-02-07 14:23 UTC
