### ISSUE TITLE
reliability of pipeline and avoid occasional github fail during helm chart push

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2327] opened 2019-01-03 13:17 UTC
! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/Activiti/activiti-cloud-helm-charts.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
make: *** [github] Error 1

**Comment by almerico** [comment] 2019-02-04 14:50
will add retries to pipelines for github push operations

**Comment by salaboy** [comment] 2019-02-08 10:27
@almerico can we close this one? please close if so

**Comment by almerico** [comment] 2019-02-08 10:29
@salaboy not yet  now I working on adding retries in pipelines to avoid accidental fall during github operations2

**Comment by ryandawsonuk** [comment] 2019-02-11 10:30
Would be good to feed the fixes back into Jenkinsfiles that JX produces. Problem is https://github.com/jenkins-x/jx/issues/2861 and variations on it.

I think we can remove GA milestone from this as it is more of an internal issue.

**Comment by ryandawsonuk** [comment] 2019-02-28 10:23
Actually 
jenkins-x/jx#2861 is a different issue about pod exec operations, not github. So I have raised https://github.com/Activiti/Activiti/issues/2582

This github one seems like something we can close now as a duplicate of https://github.com/Activiti/Activiti/issues/2528

**Comment by almerico** [comment] 2019-02-28 10:30
Yes it is better to have them separate. Do you see this one lately ?

**Comment by ryandawsonuk** [comment] 2019-02-28 10:32
Yeah raised https://github.com/Activiti/Activiti/issues/2582 because it happened to several pipelines at once this morning

**Comment by ryandawsonuk** [comment] 2019-03-06 10:08
The helm chart pushes seem stable now. I did [have to disable the helm builds for PRs](https://github.com/Activiti/Activiti/issues/2582#issuecomment-469705088) but that is a different issue. 

The need for retries with github operations more generally being tackled under https://github.com/Activiti/Activiti/issues/2599

**Closed** 2019-03-06 10:08 UTC
Labels: in progress
