### ISSUE TITLE
jdk version

### ISSUE THREAD

**Issue by qiudaoke** [Activiti/Activiti#2507] opened 2019-02-13 23:46 UTC
The JDK version currently in use in most enterprises or companies is still 8.I downloaded the GC1 version, which was compiled using jdk11。Can the GA version run on jdk8

**Comment by ryandawsonuk** [comment] 2019-02-14 09:52
We are aware of this problem - duplicate of https://github.com/Activiti/Activiti/issues/2428 Please comment there if you have suggestions or points to add

**Closed by ryandawsonuk** 2019-02-14 09:52 UTC
