### ISSUE TITLE
Name for process instances in query response not the same as RB

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1745] opened 2018-02-09 11:26 UTC
the query api return  
"_embedded": {
        "process-instances": [
            {

the runtime bundle 
{
    "_embedded": {
        "processInstanceList": [

Want to homogenise these.

We want to follow the convention camel case + simple plural, i.e, `processDefinitions`, `processInstances`, `tasks`.

I has already been fixed for process definitions in query module. In order to cover other entities you need to 
1. update [QueryRelProvider](https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/QueryRelProvider.java) to handle the desired entity
2. make sure that there is a rest doc test covering the structure for this entity. Example: https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/ProcessDefinitionAdminControllerIT.java#L107, where `pagedProcessDefinitionFields` is defined [here](https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-rest-docs/src/main/java/org/activiti/alfresco/rest/docs/HALDocumentation.java#L57)
3. you may need to add `@ExposesResourcesFor` annotation, see https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessDefinitionAdminController.java#L36.

- [x] query process definitions
- [x] query process instances
- [x] query tasks
- [x] query variables

- [x] runtime bundle process definitions
- [x] runtime bundle process instances
- [x] runtime bundle tasks
- [x] runtime bundle variables

- [x] audit events

**Comment by mauriziovitale** [comment] 2018-02-09 11:32
I guess we should always use camelcase properties

**Comment by Salaboy** [comment] 2018-03-05 08:48
@ryandawsonuk we should wait for @erdemedeiros work.. that should do the trick.

**Comment by erdemedeiros** [comment] 2018-08-14 11:05
After the latests changes the content for runtime-bundle became:
```
{
    "_embedded": {
        "cloudProcessInstanceImpls": [
            {
```
We should homogenise both query and runtime-bundle to camel case as suggested by @mauriziovitale :

```
{
    "_embedded": {
        "processInstances": [
            {
```

**Comment by Salaboy** [comment] 2018-08-14 12:52
@erdemedeiros I think that simple names such as processInstances is the best option. 
But @mauriziovitale will probably want entries (using the DBP format right?)

**Comment by erdemedeiros** [comment] 2018-08-15 09:03
@Salaboy this issue only affects HAL format. The DBP format is already fine:
```
{
    "list": {
        "entries": [
            {
                "entry": {...}
			}
	}
}
````

**Comment by salaboy** [comment] 2018-10-25 13:42
👍 closing this one then.

**Comment by erdemedeiros** [comment] 2018-11-05 13:44
@salaboy the problem is still there for HAL format.

**Comment by salaboy** [comment] 2018-11-05 14:29
@erdemedeiros reopening for beta3 then

**Comment by salaboy** [comment] 2019-01-08 12:11
@erdemedeiros can you please create a new issue for this one .. to be clear on what is missing

**Closed** 2019-01-14 09:54 UTC
Labels: api, blocking, priority1, risk
