### ISSUE TITLE
After version 5.18, the data for the server2014 SQL, start the process error

### ISSUE THREAD

**Issue by hehuafu** [Activiti/Activiti#792] opened 2016-02-01 02:59 UTC
situation
If you only pass in a variable that is successful, the two or more is reported to be wrong.
Boot code:
Map<String, Object> variables = new HashMap<String, Object>();
            String str = "002";
            variables.put("pi_applyOrgId", str);
            double d = 123;
            variables.put("price", str);
            identityService.setAuthenticatedUserId("104000209");
            //ProcessInstance processInstance = runtimeService.startProcessInstanceByKey("DPZL-001", null, variables);
            ProcessInstance processInstance = runtimeService.startProcessInstanceByKey("MyProcess", null, variables);
            identityService.setAuthenticatedUserId(null);
Error message:
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 不支持从 UNKNOWN 到 UNKNOWN 的转换。

2016-01-31 20:56:26,679 [main] WARN  ramework.test.context.TestContextManager -Caught exception while allowing TestExecutionListener [org.springframework.test.context.transaction.TransactionalTestExecutionListener@15fc5dc] to process 'after' execution for test: method [public void com.pousheng.bpms.engine.process.ProcessTest.testStartProcess()], instance [com.pousheng.bpms.engine.process.ProcessTest@b72dcb], exception [null]
org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:717)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener$TransactionContext.endTransaction(TransactionalTestExecutionListener.java:591)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.endTransaction(TransactionalTestExecutionListener.java:297)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.afterTestMethod(TransactionalTestExecutionListener.java:192)
    at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:396)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:91)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by frerichkai** [comment] 2016-03-10 14:41
We encountered the same error, but got it fixed by updating MyBatis to a current version.

**Comment by calbertts** [comment] 2016-04-14 20:14
I'm having the same issue, does it have something to do with the activiti tables charset?
I've been struggling with this for a long without success.

I'd really appreciate any idea guys.

**Comment by jbarrez** [comment] 2016-04-15 10:53
Did you verify you didn't override the mybatis version (as stated above) ?
Your db is running UTF8?

**Comment by calbertts** [comment] 2016-04-15 14:04
My db is using *utf8mb4*, activiti too, but I'm experiencing an intermittent issue.
Sometimes our workflows just fail with this error but with this character: '\\xA0 \\x0A' which is a non-breaking space, the weird thing is that if I try to insert that character directly in the DB it works fine, because it's supposed utf8mb4 supports it.

Once it starts to happen, doesn't work anymore.

I've been trying to reproduce it without success, I'm using Activiti 5.18.
Reading this I thought maybe upgrading mybatis version the issue was going to disappear, but it seems Activiti  5.18 is not compatible with mybatis 3.3.1

**Comment by luojims** [comment] 2016-06-30 07:43
I met similar problems to add Bpmn when using the sqlserver. I have found since version 5.18 added blukXXX insert statement. But sqlServer is nonsupport` insert into table(col1, col2) value (value1, value2), (value3, value4)`. I don't know whether there was a way to solve this.

**Comment by Salaboy** [comment] 2017-08-30 14:28
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.

**Closed by Salaboy** 2017-08-30 14:28 UTC
