### ISSUE TITLE
when i drag the Lane into the center......

### ISSUE THREAD

**Issue by cutemurphy** [Activiti/Activiti#965] opened 2016-07-27 12:07 UTC
when i drag the Lane into the center......

there is a  js error occur...........

what is the reason of this...

![33](https://cloud.githubusercontent.com/assets/1875062/17174649/9a22348e-5435-11e6-8894-f4e475e247e1.png)

**Comment by Salaboy** [comment] 2017-11-21 20:13
closing this because designer doesn't belong to this repository anymore, please feel free to re-open if this is still an issue.

**Closed by Salaboy** 2017-11-21 20:13 UTC

**Comment by SDhalor** [comment] 2017-12-12 13:36
The issue still persists. Any work around??

**Comment by Salaboy** [comment] 2017-12-12 13:52
@SDhalor hi there, thanks for getting in touch. Can you please specify in which version you are still experiencing the issue? 

Cheers

**Comment by SDhalor** [comment] 2017-12-12 13:56
version 6. it is exactly the same issue shown in screenshot.

**Comment by Salaboy** [comment] 2017-12-12 15:31
@SDhalor is 6 Final? or beta4? Please answer with the exact version. Did you find out what the issue is exactly? In the source code (6.x) branch?

**Comment by SDhalor** [comment] 2017-12-12 15:37
6.X branch of this project. Check line number 23397 of oryx.debug.js

**Comment by Salaboy** [comment] 2017-12-12 15:47
https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-ui/activiti-app/src/main/webapp/editor/editor-app/editor/oryx.debug.js#L23397
You are right the issue might be in that function. Are you willing to contribute with the solution? It seems that you already manage to scope it quite correctly, and we will appreciate a PR fixing that problem.
