### ISSUE TITLE
REST: includeProcessVariables query parameter doesn't work when GET-in single instance

### ISSUE THREAD

**Issue by villuv** [Activiti/Activiti#571] opened 2015-04-17 10:12 UTC
Using version **5.17.0**

For example

`GET ... /runtime/process-instances?includeProcessVariables=true`

returns a list of process instances with vairables filled, but

`GET .../runtime/process-instances/40004?includeProcessVariables=true`

returns a single process instance with `variables` attribute an empty array regardless of the value of `includeProcessVariables` query parameter.

**Comment by vickysirwani** [comment] 2015-07-04 16:37
@jbarrez Please confirm if this is expected behavior? If not I can push a fix for this.

**Comment by CoachHockey** [comment] 2017-08-15 19:57
Bumping - would like to see developer input on this.  The issue is the same for 

`GET .../runtime/tasks/<taskId>?includeProcessVariables=true`

**Comment by Salaboy** [comment] 2017-08-20 08:47
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding

**Closed by Salaboy** 2017-08-20 08:47 UTC
