### ISSUE TITLE
BUG：when task Completed，error：Variable assigneeList' is not a Collection

### ISSUE THREAD

**Issue by cverdela** [Activiti/Activiti#2362] opened 2019-01-14 04:04 UTC
when `taskService.complete()` , variable assigneeList is not a ArrayList but a ArrayNode,
at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveAndValidateCollection(MultiInstanceActivityBehavior.java:225)
in Activiti7
ps. <multiInstanceLoopCharacteristics isSequential="false"
     activiti:collection="assigneeList" activiti:elementVariable="assignee" >

**Comment by cverdela** [comment] 2019-01-14 04:05
```
 <multiInstanceLoopCharacteristics isSequential="false"
     activiti:collection="assigneeList" activiti:elementVariable="assignee" >
```

**Comment by salaboy** [comment] 2019-01-17 13:01
closing as it is a duplicate of #2364 ,
thanks for reporting. A work around is to disable the JSON variable serialization. Look at the other issue suggestion

**Closed by salaboy** 2019-01-17 13:01 UTC

**Comment by ming820214** [comment] 2022-11-25 02:56
> assigneeList

the " trying with spring.activiti.serializePOJOsInVariablesToJson=false in the properties file" not valid，
