### ISSUE TITLE
Upgrade script for mssql 8.0.0 to 8.1.0 has syntax error

### ISSUE THREAD

**Issue by robrorijeloxia** [Activiti/Activiti#4542] opened 2024-01-17 12:58 UTC
The script has an extra 'column', which is not used in mssql (this is different in other dialects of sql):
`alter table ACT_HI_IDENTITYLINK add column DETAILS_ varbinary(max);`

See: https://learn.microsoft.com/en-us/sql/relational-databases/tables/add-columns-to-a-table-database-engine?view=sql-server-ver16#add-columns-to-a-table

**Comment by swaroopar** [comment] 2024-01-24 04:04
duplicate of https://github.com/Activiti/Activiti/issues/4491 
unfortunately no fix yet. All releases from 8.1.0 are unsuable with MySql.

**Comment by robrorijeloxia** [comment] 2024-01-24 07:50
This is a different issue though, this is for Microsoft Sql server, not Mysql. I have a fix, just doublechecking if it solves the problem

**Comment by swaroopar** [comment] 2024-01-27 09:38
> This is a different issue though, this is for Microsoft Sql server, not Mysql. I have a fix, just doublechecking if it solves the problem

@robrorijeloxia ah yes, sorry. I misunderstood the issue title. Indeed a different issue.

**Closed as completed** 2024-02-06 17:43 UTC
