### ISSUE TITLE
use 6.0.0 and jstl have debugger，how resolve it

### ISSUE THREAD

**Issue by kindperson** [Activiti/Activiti#1523] opened 2017-10-27 06:15 UTC
[DEBUG] loaded class javax.servlet.jsp.tagext.TagSupport from ClassRealm[plugin>org.eclipse.jetty:jetty-maven-plugin:9.2.7.v20150116, parent: sun.misc.Launcher$AppClassLoader@18b4aac2]
[DEBUG] loaded class org.springframework.web.servlet.tags.RequestContextAwareTag from WebAppClassLoader=1168942230@45aca496
[DEBUG] loaded class org.springframework.web.servlet.tags.HtmlEscapingAwareTag from WebAppClassLoader=1168942230@45aca496
[DEBUG] loaded class org.springframework.web.servlet.tags.MessageTag from WebAppClassLoader=1168942230@45aca496
[WARNING] EXCEPTION 
javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.jasper.el.ELContextImpl
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:358)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.error(Dispatcher.java:77)
	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:91)
	at org.eclipse.jetty.server.Response.sendError(Response.java:597)
	at org.eclipse.jetty.server.Response.sendError(Response.java:544)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:647)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.jasper.el.ELContextImpl
	at org.apache.jasper.compiler.Validator$ValidateVisitor.getJspAttribute(Validator.java:1414)
	at org.apache.jasper.compiler.Validator$ValidateVisitor.checkXmlAttributes(Validator.java:1231)
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:879)
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1521)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2361)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2413)
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2419)
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:464)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2361)
	at org.apache.jasper.compiler.Validator.validateExDirectives(Validator.java:1846)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:217)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:564)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:405)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:349)
	... 36 more
[DEBUG] org.eclipse.jetty.server.HttpConnection$SendCallback@150d3676[PROCESSING][i=ResponseInfo{HTTP/1.1 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@31acbe03] generate: NEED_HEADER (null,[p=0,l=0,c=0,r=0],true)@START
[DEBUG] org.eclipse.jetty.server.HttpConnection$SendCallback@150d3676[PROCESSING][i=ResponseInfo{HTTP/1.1 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@31acbe03] generate: FLUSH ([p=0,l=142,c=8192,r=142],[p=0,l=0,c=0,r=0],true)@COMPLETING
[DEBUG] write: WriteFlusher@1f01fe03{IDLE} [HeapByteBuffer@3a9b21ec[p=0,l=142,c=8192,r=142]={<<<HTTP/1.1 500 Serv....v20150116)\r\n\r\n>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}]
[DEBUG] update WriteFlusher@1f01fe03{WRITING}:IDLE-->WRITING
[DEBUG] flushed 142 SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,Open,in,out,-,W,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] update WriteFlusher@1f01fe03{IDLE}:WRITING-->IDLE
[DEBUG] org.eclipse.jetty.server.HttpConnection$SendCallback@150d3676[PROCESSING][i=ResponseInfo{HTTP/1.1 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@31acbe03] generate: SHUTDOWN_OUT ([p=142,l=142,c=8192,r=0],[p=0,l=0,c=0,r=0],true)@END
[DEBUG] org.eclipse.jetty.server.HttpConnection$SendCallback@150d3676[PROCESSING][i=ResponseInfo{HTTP/1.1 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@31acbe03] generate: DONE ([p=142,l=142,c=8192,r=0],[p=0,l=0,c=0,r=0],true)@END
[DEBUG] oshut SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,Open,in,out,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] RESPONSE /sso/login  500 handled=true
[DEBUG] HttpChannelState@1af02a34{s=DISPATCHED i=true a=null} unhandle DISPATCHED
[DEBUG] close HttpParser{s=END,0 of 0}
[DEBUG] END --> CLOSED
[DEBUG] HttpChannelOverHttp@66583019{r=1,c=false,a=IDLE,uri=-} handle exit, result COMPLETE
[DEBUG] filled -1 SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,Open,in,OSHUT,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] ishut SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,Open,in,OSHUT,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] onClose SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,CLOSED,ISHUT,OSHUT,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] close SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,CLOSED,ISHUT,OSHUT,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] Destroyed SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,CLOSED,ISHUT,OSHUT,-,-,0,HttpConnection}{io=0,kio=-1,kro=-1}
[DEBUG] onClose HttpConnection@117acb91{FILLING}
[DEBUG] onClose SelectChannelEndPoint@5ab5b{/127.0.0.1:54923<->1111,CLOSED,ISHUT,OSHUT,-,-,0,HttpConnection}{io=0,kio=-1,kro=-1}
[DEBUG] atEOF HttpParser{s=CLOSED,0 of 0}
[DEBUG] parseNext s=CLOSED HeapByteBuffer@444bef13[p=0,l=0,c=16384,r=0]={<<<>>>GET /sso/login HT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
[DEBUG] FILLING-->IDLE HttpConnection@117acb91{IDLE}
[DEBUG] Scavenging sessions at 1509084758929
[DEBUG] Selector loop woken up from select, 1/1 selected
[DEBUG] Key interests updated 1 -> 0 on SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,Open,in,out,R,-,0,HttpConnection}{io=1,kio=0,kro=1}
[DEBUG] Local interests updating 1 -> 0 for SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,Open,in,out,R,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] Running change org.eclipse.jetty.io.SelectChannelEndPoint$1@2199fa42
[DEBUG] FILL_INTERESTED-->FILLING HttpConnection@4f9f981f{FILLING}
[DEBUG] Selector loop waiting on select
[DEBUG] HttpConnection@4f9f981f{FILLING} onFillable HttpChannelState@1f9994a5{s=IDLE i=true a=null}
[DEBUG] filled -1 SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,Open,in,out,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] ishut SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,Open,in,out,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] atEOF HttpParser{s=START,0 of 0}
[DEBUG] parseNext s=START HeapByteBuffer@444bef13[p=0,l=0,c=16384,r=0]={<<<>>>GET /sso/login HT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
[DEBUG] START --> CLOSED
[DEBUG] onClose SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,CLOSED,ISHUT,out,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] close SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,CLOSED,ISHUT,out,-,-,0,HttpConnection}{io=0,kio=0,kro=1}
[DEBUG] Destroyed SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,CLOSED,ISHUT,OSHUT,-,-,0,HttpConnection}{io=0,kio=-1,kro=-1}
[DEBUG] onClose HttpConnection@4f9f981f{FILLING}
[DEBUG] onClose SelectChannelEndPoint@48c40745{/127.0.0.1:54924<->1111,CLOSED,ISHUT,OSHUT,-,-,0,HttpConnection}{io=0,kio=-1,kro=-1}
[DEBUG] FILLING-->IDLE HttpConnection@4f9f981f{IDLE}
[DEBUG] loaded class org.apache.commons.pool2.impl.EvictionConfig from WebAppClassLoader=1168942230@45aca496
[DEBUG] loaded class org.apache.commons.pool2.impl.BaseGenericObjectPool$EvictionIterator from WebAppClassLoader=1168942230@45aca496
[DEBUG] loaded class org.apache.commons.pool2.impl.LinkedBlockingDeque$AbstractItr from WebAppClassLoader=1168942230@45aca496
[DEBUG] loaded class org.apache.commons.pool2.impl.LinkedBlockingDeque$DescendingItr from WebAppClassLoader=1168942230@45aca496
[DEBUG] Scavenging sessions at 1509084788930
[DEBUG] Scavenging sessions at 1509084818931

**Comment by Salaboy** [comment] 2017-11-28 15:56
@kindperson hi there. you need to be more detailed while reporting bugs/issues. This stacktrace doesn't explain too much and the problem is clearly related with: **"javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.jasper.el.ELContextImpl"**. Unfortunately, with this amount of information it is impossible to help you. I'm closing the issue now, but please feel free to reopen if you can provide more context.

**Closed by Salaboy** 2017-11-28 15:56 UTC
