### ISSUE TITLE
spring4.1.x Compatibility problems

### ISSUE THREAD

**Issue by cshuig** [Activiti/Activiti#631] opened 2015-06-28 00:15 UTC
class：org.activiti.rest.editor.model.ModelSaveRestResource
methon: saveModel

when i use 4.0.x, it is work fine, but replaced by spring 4.1.x, will error
error content:
Failed to evaluate serialization for type [void]: java.lang.IllegalStateException: Failed to instantiate standard serializer (of type com.fasterxml.jackson.databind.ser.std.NullSerializer): Class com.fasterxml.jackson.databind.ser.BasicSerializerFactory can not access a member of class com.fasterxml.jackson.databind.ser.std.NullSerializer with modifiers "private"

**Comment by jbarrez** [comment] 2015-07-02 09:25
Yes, this is a known thing. We'll solve it when we upgrade the Spring dependencies. It needs and @ResponseStatus annotaton.

**Comment by tijsrademakers** [comment] 2015-08-04 07:05
Fixed in 5.18.0

**Comment by Salaboy** [comment] 2017-08-20 08:49
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding

**Closed by Salaboy** 2017-08-20 08:49 UTC
