### ISSUE TITLE
Standardise modeling service path

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#2419] opened 2019-01-25 12:44 UTC
For backend:
  ${gatewayUrl}/activiti-cloud-modeling-backend
should become:
  ${gatewayUrl}/modeling-service

and for front-end:
  ${gatewayUrl}/activiti-cloud-modeling
should become:
  ${gatewayUrl}/modeling

and API_URL should be the only var passed to front-end with /modeling-service as prefix as agreed with @popovicsandras

**Comment by ryandawsonuk** [comment] 2019-01-25 13:14
You'll need to change the chart to support that as `-backend` is hardcoded into the way it works https://github.com/Activiti/activiti-cloud-charts/blob/master/activiti-cloud-modeling/templates/service-backend.yaml#L5

**Comment by salaboy** [comment] 2019-03-10 10:03
@mteodori what is the status of this issue?

**Comment by mteodori** [comment] 2019-03-11 07:55
it was more difficult than estimated due the complexity of the frontend/backend in one container setup, I can try and give it another go

**Comment by salaboy** [comment] 2019-03-13 09:21
ok I will leave open

**Comment by salaboy** [comment] 2019-05-08 16:22
closing as it is a duplicate of: https://github.com/Activiti/Activiti/issues/2733

**Closed by salaboy** 2019-05-08 16:22 UTC
