### ISSUE TITLE
TaskRuntime api always replace the assignee param in payload

### ISSUE THREAD

**Issue by sayakadead** [Activiti/Activiti#2531] opened 2019-02-20 04:51 UTC
I want to find running tasks in a process instance by use the code below:
```
taskRuntime.tasks(Pageable.of(0, 10), TaskPayloadBuilder.tasks().withProcessInstanceId(processInstanceId).build());
```
But it return a empty list. I check the code in TaskRuntimeImpl.tasks(Pageable pageable, GetTasksPayload getTasksPayload) method and found that it always replace the assigneeId param in payload with securityManager.getAuthenticatedUserId()
```
//...
String authenticatedUserId = securityManager.getAuthenticatedUserId();
if (authenticatedUserId != null && !authenticatedUserId.isEmpty()) {
    List<String> userGroups = userGroupManager.getUserGroups(authenticatedUserId);
    getTasksPayload.setAssigneeId(authenticatedUserId);
    getTasksPayload.setGroups(userGroups);
    //...
} else {
    throw new IllegalStateException("You need an authenticated user to perform a task query");
}
```
The source value of assigneeId param in payload is never use, this may get confusing. I think it's better to remove this param in payload, or use the source value instead of securityManager.getAuthenticatedUserId() if user call tasks method with a non-null getTasksPayload param.

The claim(ClaimTaskPayload claimTaskPayload) method in TaskRuntimeImpl also have the same problem.

**Comment by salaboy** [comment] 2019-02-21 13:49
@sayakadead that is the expected behaviour, the new APIs takes the currently logged user as the user making the request. Notice that the TaskRuntime API is for executing operations not regular queries. 
We are not providing a query API similar to the HistoryService in 6.x yet, because for the cloud approach we have the Query Service for that purpose. 

Also notice that you have the TaskAdminRuntime which have access to all tasks and not only the ones bounded to the specific user doing the call, but in order to invoke that API the user must have the ACTIVITI_ADMIN role.

**Comment by salaboy** [comment] 2019-03-11 10:58
I am closing this issue because the question was answered.

**Closed by salaboy** 2019-03-11 10:58 UTC
Labels: question
