### ISSUE TITLE
Nullpointer exception in AsyncExecutor when running concurrent tasks for a process that has all tasks async

### ISSUE THREAD

**Issue by harshvardhanv** [Activiti/Activiti#1902] opened 2018-05-25 12:04 UTC
We have a process with 14+ async tasks that are mutually inclusive (need to run one after the other) 

The reason for async is to be be able to get a processInstanceId returned when starting the run.

But as we start to run this process with multiple hits, we start seeing the following error :

java.lang.NullPointerException: null
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:151) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:35) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.persistence.entity.AbstractEntityManager.delete(AbstractEntityManager.java:87) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:137) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:35) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.persistence.entity.AbstractEntityManager.delete(AbstractEntityManager.java:82) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.unacquire(DefaultJobManager.java:230) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable$3.execute(ExecuteAsyncRunnable.java:169) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable$3.execute(ExecuteAsyncRunnable.java:167) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63) ~[activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) [activiti-spring-6.0.0.jar:6.0.0]
                at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
                at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) [activiti-spring-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29) [activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44) [activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) [activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.unacquireJob(ExecuteAsyncRunnable.java:167) [activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.lockJobIfNeeded(ExecuteAsyncRunnable.java:154) [activiti-engine-6.0.0.jar:6.0.0]
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:72) [activiti-engine-6.0.0.jar:6.0.0]
                at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
 
Exception in thread "SimpleAsyncTaskExecutor-172" java.lang.NullPointerException
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:151)
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:35)
                at org.activiti.engine.impl.persistence.entity.AbstractEntityManager.delete(AbstractEntityManager.java:87)
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:137)
                at org.activiti.engine.impl.persistence.entity.JobEntityManagerImpl.delete(JobEntityManagerImpl.java:35)
                at org.activiti.engine.impl.persistence.entity.AbstractEntityManager.delete(AbstractEntityManager.java:82)
                at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.unacquire(DefaultJobManager.java:230)
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable$3.execute(ExecuteAsyncRunnable.java:169)
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable$3.execute(ExecuteAsyncRunnable.java:167)
                at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37)
                at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78)
                at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
                at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
                at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
                at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
                at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
                at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
                at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
                at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
                at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
                at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.unacquireJob(ExecuteAsyncRunnable.java:167)
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.lockJobIfNeeded(ExecuteAsyncRunnable.java:154)
                at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:72)
                at java.lang.Thread.run(Thread.java:745)

**Comment by Salaboy** [comment] 2018-06-05 08:27
@balsarori does this ring a bell?

**Comment by balsarori** [comment] 2018-06-05 09:21
@Salaboy no bells :)
@harshvardhanv is possible to share your process definition?

**Comment by harshvardhanv** [comment] 2018-06-08 11:15
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
	xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
	typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath"
	targetNamespace="http://www.activiti.org/test">

	<process id="Extract" name="AssetIngestion" isExecutable="true">

		<startEvent id="startevent1" name="Start"></startEvent>
		<sequenceFlow id="flow1" sourceRef="startevent1"
			targetRef="servicetask1"></sequenceFlow>

		<serviceTask id="servicetask1" name="attachNullObject"
			activiti:expression="#{bean.execute()}"
			activiti:resultVariableName="beanExec1" activiti:async="true"/>
		<sequenceFlow id="flow2" sourceRef="servicetask1"
			targetRef="processIdentifierLogStatement"></sequenceFlow>

		<scriptTask id="processIdentifierLogStatement" name="processIdentifierLogStatement"
			activiti:async="true" scriptFormat="JavaScript">
			<script>
				var processName = execution.getVariable("processName");
				var
				logText = "Process name is " + processName;
				execution.setVariable("processIdentifierLogStatement",logText);
			</script>
		</scriptTask>
		<sequenceFlow id="seqFlow" sourceRef="processIdentifierLogStatement"
			targetRef="logStartProcessExtraction"></sequenceFlow>
		<serviceTask id="logStartProcessExtraction" name="logStartProcessExtraction"
			activiti:expression="#{svc.insert(execution.getProcessInstanceId(),processIdentifierLogStatement)}"
			activiti:async="true"/>
		<sequenceFlow id="logsForProcess" sourceRef="logStartProcessExtraction"
			targetRef="servicetask2"></sequenceFlow>

		<serviceTask id="servicetask2" name="ProcessExecution"
			activiti:expression="#{call(commandID,execution.getProcessInstanceId())}"
			activiti:resultVariableName="responseJson" activiti:async="true"></serviceTask>
		<sequenceFlow id="flow3" sourceRef="servicetask2"
			targetRef="exceptionHandlingForProcessExecution"></sequenceFlow>

		<serviceTask id="exceptionHandlingForProcessExecution"
			name="exceptionHandlingForProcessExecution" activiti:expression="#{exceptionBehavior.execute(responseJson)}"
			activiti:resultVariableName="exceptionStatusForProcessExecution"
			activiti:async="true">
		</serviceTask>
		<sequenceFlow id="checkExceptionForProcessExecution"
			sourceRef="exceptionHandlingForProcessExecution" targetRef="exceptionOccuredForProcessExecution"></sequenceFlow>

		<exclusiveGateway id="exceptionOccuredForProcessExecution"
			name="exceptionOccuredForProcessExecution" activiti:async="true" />
		<sequenceFlow id="exceptionForProcessExecution"
			sourceRef="exceptionOccuredForProcessExecution" targetRef="catchException">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForProcessExecution == "HandleException"}]]>
			</conditionExpression>
		</sequenceFlow>
		<sequenceFlow id="no-exceptionForProcessExecution"
			sourceRef="exceptionOccuredForProcessExecution" targetRef="servicetask3">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForProcessExecution == "NoException"}]]>
			</conditionExpression>
		</sequenceFlow>

		<serviceTask id="servicetask3" name="ExtractS95"
			activiti:expression="#{extractAsset.extractJsonFieldWrapper(responseJson,execution.getProcessInstanceId(),&quot;$.s95&quot;)}"
			activiti:resultVariableName="s95Json" activiti:async="true"></serviceTask>
		<sequenceFlow id="flow4" sourceRef="servicetask3"
			targetRef="exceptionHandlingForExtractS95"></sequenceFlow>

		<serviceTask id="exceptionHandlingForExtractS95" name="exceptionHandlingForExtractS95"
			activiti:expression="#{exceptionBehavior.execute(s95Json)}"
			activiti:resultVariableName="exceptionStatusForExtractS95"
			activiti:async="true">
		</serviceTask>
		<sequenceFlow id="checkExceptionForExtractS95" sourceRef="exceptionHandlingForExtractS95"
			targetRef="exceptionOccuredForExtractS95"></sequenceFlow>
		<exclusiveGateway id="exceptionOccuredForExtractS95"
			name="exceptionOccured" activiti:async="true" />
		<sequenceFlow id="exceptionForExtractS95" sourceRef="exceptionOccuredForExtractS95"
			targetRef="catchException">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForExtractS95 == "HandleException"}]]>
			</conditionExpression>
		</sequenceFlow>
		<sequenceFlow id="no-exceptionForExtractS95" sourceRef="exceptionOccuredForExtractS95"
			targetRef="ExtractProcessSourceKey">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForExtractS95 == "NoException"}]]>
			</conditionExpression>
		</sequenceFlow>


		<serviceTask id="ExtractProcessSourceKey" name="ExtractProcessSourceKey"
			activiti:expression="#{extractJsonPathTask.extractJsonFieldWrapper(responseJson,execution.getProcessInstanceId(),&quot;$.s95.instances[?(@.classification=='CPM_Process')].id&quot;)}"
			activiti:resultVariableName="processSourceKeyArray" activiti:async="true"></serviceTask>
		<sequenceFlow id="ProcessFlow" sourceRef="ExtractProcessSourceKey"
			targetRef="exceptionHandlingForFetchingProcessSourceKey"></sequenceFlow>

		<serviceTask id="exceptionHandlingForFetchingProcessSourceKey"
			name="exceptionHandlingForFetchingProcessSourceKey"
			activiti:expression="#{exceptionBehavior.execute(processSourceKeyArray)}"
			activiti:resultVariableName="exceptionStatusForFetchingProcessSourceKey"
			activiti:async="true">
		</serviceTask>
		<sequenceFlow id="checkExceptionForFetchingProcessSourceKey"
			sourceRef="exceptionHandlingForFetchingProcessSourceKey" targetRef="exceptionOccuredForFetchingProcessSourceKey"></sequenceFlow>
		<exclusiveGateway id="exceptionOccuredForFetchingProcessSourceKey"
			name="exceptionOccured" activiti:async="true" />
		<sequenceFlow id="exceptionForFetchingProcessSourceKey"
			sourceRef="exceptionOccuredForFetchingProcessSourceKey" targetRef="catchException">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForFetchingProcessSourceKey == "HandleException"}]]>
			</conditionExpression>
		</sequenceFlow>
		<sequenceFlow id="no-exceptionForFetchingProcessSourceKey"
			sourceRef="exceptionOccuredForFetchingProcessSourceKey" targetRef="GetProcessSourceKeyValue">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForFetchingProcessSourceKey == "NoException"}]]>
			</conditionExpression>
		</sequenceFlow>

		<scriptTask id="GetProcessSourceKeyValue" name="GetProcessSourceKeyValue"
			activiti:async="true" scriptFormat="JavaScript">
			<script>
				var
				jsonArrayString=execution.getVariable("processSourceKeyArray");
				var
				jsonArray=JSON.parse(jsonArrayString);
				var firstValue=jsonArray[0];
				if(firstValue)
				execution.setVariable("processSourceKey",firstValue);
				else
				execution.setVariable("processSourceKey","HandleException");
			</script>
		</scriptTask>
		<sequenceFlow id="ProcessSourceKeyValueFlow" sourceRef="GetProcessSourceKeyValue"
			targetRef="handleExceptionForPD"></sequenceFlow>

		<serviceTask id="handleExceptionForPD"
			name="handleExceptionForPD"
			activiti:expression="#{exceptionBehavior.execute(processSourceKey)}"
			activiti:resultVariableName="exceptionStatusForGetProcessSourceKeyValue"
			activiti:async="true">
		</serviceTask>
		<sequenceFlow id="checkExceptionForGetProcessSourceKeyValue"
			sourceRef="handleExceptionForPD" targetRef="exceptionOccuredForGetProcessSourceKeyValue"></sequenceFlow>
		<exclusiveGateway id="exceptionOccuredForGetProcessSourceKeyValue"
			name="exceptionOccured" activiti:async="true" />
		<sequenceFlow id="exceptionForGetProcessSourceKeyValue"
			sourceRef="exceptionOccuredForGetProcessSourceKeyValue" targetRef="catchException">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForGetProcessSourceKeyValue == "HandleException"}]]>
			</conditionExpression>
		</sequenceFlow>
		<sequenceFlow id="no-exceptionForGetProcessSourceKeyValue"
			sourceRef="exceptionOccuredForGetProcessSourceKeyValue" targetRef="createJsonPathMappingTask">
			<conditionExpression xsi:type="tFormalExpression"><![CDATA[${exceptionStatusForGetProcessSourceKeyValue == "NoException"}]]>
			</conditionExpression>
		</sequenceFlow>

		<serviceTask id="createJsonPathMappingTask" name="createJsonPathMappingTask"
			activiti:expression="#{evaluate.eval(execution.getProcessInstanceId(),parentSourceKey)}"
			activiti:resultVariableName="inOutMapping" activiti:async="true"></serviceTask>
		<sequenceFlow id="createJsonPathMappingFlow" sourceRef="createJsonPathMappingTask"
			targetRef="endevent"></sequenceFlow>


		<endEvent id="endevent" name="End"></endEvent>
	</process>
</definitions>

**Comment by harshvardhanv** [comment] 2018-06-08 11:15
It also comes in the simplest of definitions. (Eg. 2 serviceTasks marked as async="true")

**Comment by Salaboy** [comment] 2018-06-08 12:17
@balsarori might it be related with the number of executor threads?

**Comment by balsarori** [comment] 2018-06-08 13:37
Seems it's a race condition multiple threads are creating/deleting jobs concurrently. I guess the issue is due to SimpleAsyncTaskExecutor executing tasks concurrently. Can you try switching off concurrency 

https://docs.spring.io/autorepo/docs/spring-framework/3.2.8.RELEASE/javadoc-api/org/springframework/core/task/SimpleAsyncTaskExecutor.html#NO_CONCURRENCY

**Comment by daisuke-yoshimoto** [comment] 2018-06-12 21:55
@balsarori 
If set NO_CONCURRENCY, Spring Boot will not be able to start because at least 4 thread are need.
* activiti-acquire-timer-jobs(AcquireTimerJobsRunnable)
* activiti-acquire-async-jobs(AcquireAsyncJobsDueRunnable)
* activiti-reset-expired-jobs(ResetExpiredJobsRunnable)
* Thread for executing job(ExecuteAsyncRunnable)

Also, even if hold down to 4 threads, the bug is be reproduced.

**Comment by balsarori** [comment] 2018-06-13 09:13
Thanks for the info @daisuke-yoshimoto 

Do you know if this issue is reproducible when not using spring boot?

**Comment by daisuke-yoshimoto** [comment] 2018-06-13 09:17
@balsarori 
Yeah. I reproduced this bug with spring boot.
Should I upload the reproducible project?

**Comment by daisuke-yoshimoto** [comment] 2018-06-13 09:28
@balsarori 
Sorry, I misunderstodd. I wll try to investigate it.

**Comment by daisuke-yoshimoto** [comment] 2018-06-13 11:55
@balsarori 
 I reproduced this bug with activiti-app.

**Comment by daisuke-yoshimoto** [comment] 2018-06-14 13:57
@Salaboy @balsarori 
Sorry I made you wait. I understood the cause.
This is about the transaction issue of activiti-spring.
In order to solve it, we should use @TransactionalEventListener like Activiti7.

In Activiti's job mechanism, there are two timings to process jobs.
1. Add the job directly to the AsyncExecutor when the completion of the thread
-> AsyncJobAddedNotification(CommandContextCloseListener) adds the job to the AsyncExecutor after closing command. AsyncExecutor processes jobs in a separate thread.

2. Daemon thread adds the job to the AsyncExecutor.
-> AcquireAsyncJobsDueRunnable(Daemon thread) get jobs from table(act_ru_job) and adds the job to the AsyncExecutor.

The problem of this time is case 1.
Originally, AsyncJobAddedNotification should add the job to the AsyncExecutor after transaction commit. But, in case of activiti-spring, AsyncJobAddedNotification add the job to the AsyncExecutor even if transaction is not completed.So,job is executed by another thread before the transaction is commited, and a record of the job before commitment can not be referenced by another thread, and NullPointerException occurs.
https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-engine/src/main/java/org/activiti/engine/impl/jobexecutor/AsyncJobAddedNotification.java#L44
https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-spring/src/main/java/org/activiti/spring/SpringTransactionInterceptor.java#L47

**Comment by daisuke-yoshimoto** [comment] 2018-06-14 14:58
@Salaboy @balsarori 
I started fixing this issue.
https://github.com/Activiti/Activiti/pull/1912

**Comment by daisuke-yoshimoto** [comment] 2018-06-15 12:09
Reproduction test
https://github.com/daisuke-yoshimoto/activiti-spring-boot-job-load-test

**Comment by harshvardhanv** [comment] 2018-06-18 08:57
@daisuke-yoshimoto  Is the fix going to be available in a release soon ?

**Comment by daisuke-yoshimoto** [comment] 2018-06-18 09:03
@harshvardhanv 
Although I have confirmed that this bug does not occur by this modification, the formal flow is awaiting review status.

**Comment by harshvardhanv** [comment] 2018-06-29 09:48
is this through ?

**Comment by daisuke-yoshimoto** [comment] 2018-06-29 15:04
@Salaboy @balsarori 
If possible, please review this one.
https://github.com/Activiti/Activiti/pull/1912

**Comment by Salaboy** [comment] 2018-07-13 07:08
@balsori needs to review and merge this one.

**Comment by balsarori** [comment] 2018-08-20 13:19
#1912 merged.

**Closed by balsarori** 2018-08-20 13:19 UTC
Labels: bug
