### ISSUE TITLE
Migration - Error when migration jobs from Activiti 5.21.0 to Activiti 6

### ISSUE THREAD

**Issue by minhquankq** [Activiti/Activiti#1310] opened 2017-07-31 06:02 UTC
Hi all,
I have handled migration activiti from 5.21.0 to 6.0.0 by guide from https://www.activiti.org/migration.html
(I have updated  file `activiti-rest/WEB-INF/classes/activiti-custom-context.xml` to set activiti5CompatibilityEnabled and activiti5CompatibilityHandlerFactory
```
<bean id="activiti5CompabilityFactory" class="org.activiti.compatibility.spring.SpringActiviti5CompatibilityHandlerFactory" />
<bean id="processEngineConfiguration" class="org.activiti.spring.SpringProcessEngineConfiguration">
   .........
    <property name="activiti5CompatibilityEnabled" value="true" />
    <property name="activiti5CompatibilityHandlerFactory" ref="activiti5CompabilityFactory" />
</bean>
``` 
 and copy activiti5-compatibility-6.0.0.jar, activiti5-engine-6.0.0.jar, activiti5-spring-6.0.0.jar, activiti5-spring-compatibility-6.0.0.jar to activiti-rest's libs)

But when starting the server (tomcat), I got some error when it run job (I have some existed job in old version), below is error log when migrate & execute job.
```
02:56:57,249 [activiti-async-job-executor-thread-1] ERROR org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable  - Job 217323 failed
java.lang.NullPointerException
  at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.executeJobHandler(DefaultJobManager.java:303)
  at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.executeTimerJob(DefaultJobManager.java:280)
  at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.execute(DefaultJobManager.java:214)
  at org.activiti.engine.impl.cmd.ExecuteAsyncJobCmd.execute(ExecuteAsyncJobCmd.java:65)
  at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
  at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
  at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
  at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
  at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
  at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
  at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:97)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:75)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
02:56:57,269 [activiti-async-job-executor-thread-2] ERROR org.activiti.engine.impl.interceptor.CommandContext  - Error while closing command context
java.lang.NullPointerException
  at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.executeJobHandler(DefaultJobManager.java:303)
  at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.executeTimerJob(DefaultJobManager.java:280)
  at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.execute(DefaultJobManager.java:214)
  at org.activiti.engine.impl.cmd.ExecuteAsyncJobCmd.execute(ExecuteAsyncJobCmd.java:65)
  at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
  at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
  at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
  at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
  at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
  at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
  at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:97)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:75)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by balsarori** [comment] 2017-07-31 10:54
duplicate of #1311

**Closed by balsarori** 2017-07-31 10:54 UTC
