### ISSUE TITLE
[activiti 6] JavaDelegate looses Expressions 

### ISSUE THREAD

**Issue by masrawi** [Activiti/Activiti#890] opened 2016-05-12 14:54 UTC
I have a JavaDelegate that sometimes has its Expressions null. digging down it seems that if the execute method takes a bit long in a high concurrency it is not able to retrieve the correct values.

```
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

import org.activiti.engine.delegate.DelegateExecution;
import org.activiti.engine.delegate.Expression;
import org.activiti.engine.delegate.JavaDelegate;
import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

@Component
@Getter
@Slf4j
public class TestGenericRestTask implements JavaDelegate
{

    private final Lock lock = new ReentrantLock();

    private Expression restApiParameter;

    @Override
    public void execute(DelegateExecution execution)
    {
        lock.lock();

        Assert.notNull(restApiParameter);
        try
        {
            Thread.sleep(2 * 1000);
            restApiParameter = null;
        }
        catch (InterruptedException e)
        {
            //ignore
        }
        finally
        {
            log.info("finishing: " + execution.getProcessInstanceId());
            lock.unlock();
        }
    }
}
```

Junit:

```
    @Test
    public void testConcurrencyTest() throws Exception
    {
        for (int i = 0; i < 2; i++)
        {
            runtimeService.startProcessInstanceByKey("conurrencyTest");
        }
        Thread.sleep(10 * 1000);
    }
```

Process:

```
  <process id="conurrencyTest" name="conurrencyTest" isExecutable="true">
    <serviceTask id="servicetask1" name="WF finish" activiti:async="true" activiti:delegateExpression="${testGenericRestTask}">
      <extensionElements>
        <activiti:field name="restApiParameter">
          <activiti:string><![CDATA[processOrderId]]></activiti:string>
        </activiti:field>
        <activiti:failedJobRetryTimeCycle>R5/PT1M</activiti:failedJobRetryTimeCycle>
      </extensionElements>
    </serviceTask>
    <sequenceFlow id="flow2" sourceRef="servicetask1" targetRef="endevent1"></sequenceFlow>
    <endEvent id="endevent1" name="End" activiti:async="true"></endEvent>
    <startEvent id="startevent1" name="Start" activiti:async="true"></startEvent>
    <sequenceFlow id="flow12" sourceRef="startevent1" targetRef="servicetask1"></sequenceFlow>
  </process>
```

**Comment by jbarrez** [comment] 2016-05-12 15:53
Why are you setting the expression to null:

restApiParameter = null;

with the lock making sure only one is executing, the second execution will always have null for the assertion (as they are singleton instances)

**Comment by masrawi** [comment] 2016-05-13 07:10
I set it to null to make sure it is initialized with the correct values every time as it has always different values.

**Comment by jbarrez** [comment] 2016-05-13 12:18
@masrawi : ok, I understand your issue now: you have a generic java delegate that you use in various process definitions. The delegate instance itself is a Spring bean (and thus a singleton).
The problem is that this setup is indeed not thread-safe: as there is but one instance of the delegate and x threads trying to inject an Expression ... this will lead to race conditions. 

Btw this is not a v6 specific feature, this is the same problem on v5.

This kind of setup is never going to work in a thread-safe way with field injection, as the delegate instance is not under control of Activiti. We'll need to document this properly and offer alternatives.

Workarounds that are currently possible:

* Have one delegate instance / {process definition, activity). This is probably not what you want when wanting to have a reusable delegate class.
* Create a new instance every time the delegateExpression is called. In Spring, this is done by switching to @Scope(SCOPE_PROTOTYPE) vs the default singleton.
* Don't use a delegateExpression, but an expression with a method: ${myBean.someMethod(execution, 'restApiParameter')}. This won't inject anything as a member and will not make the bean stateful.

If you ask me, I'd prefer the last option as it's the least invasive one.


Side information:

* For a class delegate (activiti:class), a new ClassDelegate wrapper is created once when the process definition is parsed. The fields are injected once, on instantiation. On reuse, a new ClassDelegate is created for that particular step in the process. This is not possible for a delegateExpression, as the expression could in theory produce a new delegate instance on every invocation or just one instance (like in this issue)
* Using an expression does not allow for field injection

So what will we do in the engine:

* Document the explanation above in the user guide on using delegateExpression + singleton instances 
* Add a process engine configuration flag that disables field injection on using delegateExpression. We can't just remove it, for backwards compatibility. But maybe it should be disabled by default and that people have to enable it ... not sure yet.
* Add a convenience util class that can be used in the execute() method of a delegate that reads the fieldInjection config or any extension element from the BpmnModel and returns an expression. This means that instead of injecting the expressions, the expression would have to be created in the method itself. But this would solve the thread-safety.

Thanks @masrawi for reporting this. A very interesting technical issue indeed ;-)

**Comment by roberthafner** [comment] 2016-05-13 13:42
Hi Joram,

I ran into this issue a while back as well and at that time I came up with a similar solution to what you are describing in bullet point 3. Here is an example you can share with @masrawi <https://github.com/masrawi> or include in the updated doc.

// Expose a service task factory bean to the Activiti engine.
SpringProcessEngineConfiguration config = ...
Map<Object, Object> beanMap = new HashMap<>(2);
beanMap.put(“_serviceTaskFactory", serviceTaskFactory);

ExpressionManager expressionManager = new ExpressionManager(beanMap);
config.setExpressionManager(expressionManager);

// Define get<Service>Task method(s) in the Service Task Factory.
@Component
public class ServiceTaskFactory
        implements ApplicationContextAware {

    public MailTask getMailTask() {
        return applicationContext.getBean(MailTask.class);
    }
}

// Example Service Task
@Component
@Scope(value = "prototype")
public class MailTask implements JavaDelegate {
    private Expression from;
    private Expression to;
    private Expression subject;
    private Expression message;
…
}

// Define the service task using a delegateExpression that references the method in the service task factory.
<serviceTask name="Send Mail Task" id="mailTask" activiti:delegateExpression="${_serviceTaskFactory.mailTask}”>
  <extensionElements>
    <activiti:field stringValue="john.doe@email.com" name="to" />
    <activiti:field stringValue="jane.doe@email.com" name="from"/>
    <activiti:field stringValue="Meeting" name="subject"/>
    <activiti:field stringValue="The meeting time has changed to 3pm." name="message"/>
  </extensionElements>
</serviceTask>

In terms of what to do going forward in the engine, I think it would make sense to consider adding a new type of delegate for spring beans to eliminate the need of having to use a delegateExpression. For example:

<serviceTask name="Send Mail Task" id="mailTask" activiti:delegateSpringBean="mailTask”>
  <extensionElements>
    <activiti:field stringValue="john.doe@email.com" name="to" />
    <activiti:field stringValue="jane.doe@email.com" name="from"/>
    <activiti:field stringValue="Meeting" name="subject"/>
    <activiti:field stringValue="The meeting time has changed to 3pm." name="message"/>
  </extensionElements>
</serviceTask>

Then the service task (or listener) class defined as a spring bean could decide whether its scope should be singleton or prototype accordingly.
@Bean(name = “mailTask")
@Scope(value = "prototype")
public class MailTask implements JavaDelegate {
    private Expression from;
    private Expression to;
    private Expression subject;
    private Expression message;
…
}

What do you think? (I would be willing to contribute this feature if you agree to it).

thanks,
Rob

**Comment by jbarrez** [comment] 2016-05-13 15:49
Robert, not sure why you're using the factory? You can write ${myBean} when using the SpringProcessEngineConfiguratiom and the same rules apply wrt using @Scope.

Or is this syntactic sugar? So you can use the spring bean name without wrapping it in an expression.

**Comment by roberthafner** [comment] 2016-05-13 17:17
Hi Joram,

The reason for the ServiceTaskFactory is two fold. The first is I don’t want all spring beans to be exposed as potential expression values inside the Activiti engine to avoid unforeseen namespace issues with bean names and variables. That decision forces me to define the springs beans that I wish to make available to activiti in a Map that is passed into the ExpressionManager. Autowiring the service task bean (MailTask in this case) on the class that sets up the Expression Manager and SpringProcessEngine results in a single instance of MailTask being supplied to the engine. This results in each execution of the MailTask using the same java instance. To avoid this I introduced the ServiceTaskFactory class. 

Maybe a better approach to the resolving this issue in a more general manner is to extend the ExpressionManager class to also take a list of names that could be used to restrict  the spring beans that are exposed to the activiti engine. This would eliminate the need of having to pass in the actual bean and still allow bean “filtering”.

Thoughts?

(Let me know if I am overlooking something here. )

thanks,
Rob

**Comment by masrawi** [comment] 2016-05-14 07:20
thanks @jbarrez for the thorough Explanation. I can only go with option 2 as the values of the expression is determined at design time and then deployed. all the logic is done in services outside of activiti engine. so the generic Delegate is never actually touched.

**Comment by jbarrez** [comment] 2016-05-16 09:36
Added the docs for v5 + also added a helper class  and engine config flags to do it in a thread-safe way.
Will port it to v6 tomorrow (holiday here today)

@roberthafner : will come back to your proposal after the v6 code is done.

**Comment by Salaboy** [comment] 2017-08-30 15:08
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.

**Closed by Salaboy** 2017-08-30 15:08 UTC
