### ISSUE TITLE
Date format not consistent on responses

### ISSUE THREAD

**Issue by davidcanonieto** [Activiti/Activiti#2284] opened 2018-12-18 11:22 UTC
Sometimes dates are given in milliseconds and other times in date format. See two examples above.

When updating a task:
```   "appName": "task-app",
    "appVersion": "",
    "serviceName": "task-app-rb",
    "serviceFullName": "task-app-rb",
    "serviceType": "runtime-bundle",
    "serviceVersion": "",
    "id": "68d54a8f-01f3-11e9-8e36-0a58646002ad",
    "owner": "superadminuser",
    "assignee": "superadminuser",
    "name": "This is a new task ",
    "description": "This is the description ",
    "createdDate": "2018-12-17T12:00:55.900+0000",
    "dueDate": "2018-12-18T00:00:00.000+0000",
    "priority": 0,
    "status": "ASSIGNED",
```

When getting a task by id:

```
"entry": {
        "serviceName": "task-app-rb",
        "serviceFullName": "task-app-rb",
        "serviceVersion": "",
        "appName": "task-app",
        "appVersion": "",
        "serviceType": null,
        "id": "68d54a8f-01f3-11e9-8e36-0a58646002ad",
        "assignee": "superadminuser",
        "name": "This is a new task ",
        "description": "This is the description ",
        "createdDate": 1545048055900,
        "dueDate": 1545091200000,
        "claimedDate": null,
        "priority": 0,
        "category": null,
        "processDefinitionId": null,
        "processInstanceId": null,
        "status": "ASSIGNED",
        "owner": "superadminuser",
        "parentTaskId": null,
        "formKey": null,
        "lastModified": 1545048055900,
        "lastModifiedTo": null,
        "lastModifiedFrom": null,
        "standAlone": true
    }
```

**Comment by salaboy** [comment] 2018-12-19 08:33
@davidcanonieto can you include the urls that you used for the requests? are those two answers coming from different services ?

**Comment by salaboy** [comment] 2018-12-23 12:06
Closing due cannot reproduce with Beta4. All tests in RuntimeBundle APIs and Query

- Get All My Tasks
GET {{gateway}}/rb-my-app/v1/tasks
```
{
    "_embedded": {
        "cloudTaskImpls": [
            {
                "appName": "default-app",
                "appVersion": "",
                "serviceName": "rb-my-app",
                "serviceFullName": "rb-my-app",
                "serviceType": "runtime-bundle",
                "serviceVersion": "",
                "id": "7001e71c-02c0-11e9-9a5e-0a580a180015",
                "name": "Perform action",
                "createdDate": "2018-12-18T12:28:34.765+0000",
                "priority": 50,
                "processDefinitionId": "ProcessWithVariables:1:12d29ae7-02bc-11e9-9a5e-0a580a180015",
                "processInstanceId": "700198f9-02c0-11e9-9a5e-0a580a180015",
                "status": "CREATED",
                "_links": {
                    "self": {
                        "href": "http://rb-my-app/v1/tasks/7001e71c-02c0-11e9-9a5e-0a580a180015"
                    },
                    "claim": {
                        "href": "http://rb-my-app/v1/tasks/7001e71c-02c0-11e9-9a5e-0a580a180015/claim"
                    },
                    "processInstance": {
                        "href": "http://rb-my-app/v1/process-instances/700198f9-02c0-11e9-9a5e-0a580a180015"
                    },
                    "home": {
                        "href": "http://rb-my-app/v1"
                    }
                }
            },
```
- Get By Id
GET {{gateway}}/rb-my-app/v1/tasks/{id}

- Update (priority to 12): 
PUT {{gateway}}/rb-my-app/v1/tasks/{id}
```
{
    "appName": "default-app",
    "appVersion": "",
    "serviceName": "rb-my-app",
    "serviceFullName": "rb-my-app",
    "serviceType": "runtime-bundle",
    "serviceVersion": "",
    "id": "7001e71c-02c0-11e9-9a5e-0a580a180015",
    "assignee": "hruser",
    "name": "Perform action",
    "createdDate": "2018-12-18T12:28:34.765+0000",
    "claimedDate": "2018-12-23T12:00:16.035+0000",
    "priority": 12,
    "processDefinitionId": "ProcessWithVariables:1:12d29ae7-02bc-11e9-9a5e-0a580a180015",
    "processInstanceId": "700198f9-02c0-11e9-9a5e-0a580a180015",
    "status": "ASSIGNED",
    "_links": {
        "self": {
            "href": "http://rb-my-app/v1/tasks/7001e71c-02c0-11e9-9a5e-0a580a180015"
        },
        "release": {
            "href": "http://rb-my-app/v1/tasks/7001e71c-02c0-11e9-9a5e-0a580a180015/release"
        },
        "complete": {
            "href": "http://rb-my-app/v1/tasks/7001e71c-02c0-11e9-9a5e-0a580a180015/complete"
        },
        "processInstance": {
            "href": "http://rb-my-app/v1/process-instances/700198f9-02c0-11e9-9a5e-0a580a180015"
        },
        "home": {
            "href": "http://rb-my-app/v1"
        }
    }
}
```

- Get Tasks in Query
GET {{gateway}}/query/v1/tasks

```
{
    "_embedded": {
        "tasks": [
            {
                "serviceName": "rb-my-app",
                "serviceFullName": "rb-my-app",
                "serviceVersion": "",
                "appName": "default-app",
                "appVersion": "",
                "id": "9214baf6-02bc-11e9-9a5e-0a580a180015",
                "name": "Perform action",
                "createdDate": "2018-12-18T12:00:53.940+0000",
                "priority": 50,
                "processDefinitionId": "ProcessWithVariables:1:12d29ae7-02bc-11e9-9a5e-0a580a180015",
                "processInstanceId": "920e7963-02bc-11e9-9a5e-0a580a180015",
                "status": "CREATED",
                "lastModified": "2018-12-18T12:00:53.940+0000",
                "standAlone": false,
                "_links": {
                    "self": {
                        "href": "http://query/v1/tasks/9214baf6-02bc-11e9-9a5e-0a580a180015"
                    }
                }
            },
```
- Get Task By Id in Query 
GET {{gateway}}/query/v1/tasks/

```
{
    "serviceName": "rb-my-app",
    "serviceFullName": "rb-my-app",
    "serviceVersion": "",
    "appName": "default-app",
    "appVersion": "",
    "id": "7001e71c-02c0-11e9-9a5e-0a580a180015",
    "assignee": "hruser",
    "name": "Perform action",
    "createdDate": "2018-12-18T12:28:34.765+0000",
    "claimedDate": "2018-12-23T12:00:16.035+0000",
    "priority": 12,
    "processDefinitionId": "ProcessWithVariables:1:12d29ae7-02bc-11e9-9a5e-0a580a180015",
    "processInstanceId": "700198f9-02c0-11e9-9a5e-0a580a180015",
    "status": "ASSIGNED",
    "lastModified": "2018-12-23T12:00:31.073+0000",
    "standAlone": false,
    "_links": {
        "self": {
            "href": "http://query/v1/tasks/7001e71c-02c0-11e9-9a5e-0a580a180015"
        }
    }
}
```

**Closed by salaboy** 2018-12-23 12:06 UTC
